export const CALL_REQUEST =  "CALL_REQUEST";
export const CALL_FAILED = "CALL_FAILED";
export const CALL_CONNECTED = "CALL_CONNECTED";
export const CALL_DISCONNECTED = "CALL_DISCONNECTED";
export const CALL_IN_PROGRESS = "CALL_IN_PROGRESS";