export const CALL_REQUEST =  "CALL_REQUEST";
export const CALL_FAILED = "CALL_FAILED";
export const CALL_IN_PROGRESS = "CALL_IN_PROGRESS";
export const CALL_CONNECTED = "CALL_CONNECTED";
export const CALL_DISCONNECTED = "CALL_DISCONNECTED";
export const CALL_RESET = "CALL_RESET";
export const CALL_LOG_REQUEST = "CALL_LOG_REQUEST";
export const CALL_LOG_SUCCESSFUL = "CALL_LOG_SUCCESSFUL";
export const CALL_LOG_FAILED = "CALL_LOG_FAILED";

export const CALL_CANCELED_REQUEST = "CALL_CANCELED_REQUEST";
export const CALL_CANCELED_SUCCESSFUL = "CALL_CANCELED_SUCCESSFUL";
export const CALL_CANCELED_FAILED = "CALL_CANCELED_FAILED";